create database bible;
use bible;
create table bible_quotes(book varchar(20) primary key,chapter varchar(20) not null,verse varchar(20) not null,quots varchar(100)not null);
desc bible_quotes;
insert into bible_quotes(book,chapter,verse,quots)  value 
('Genesis', 1, 1, "In the beginning God created the heavens and the earth."),
('Exodus', 14, 14, "The Lord will fight for you; you need only to be still."),
('Leviticus', 19, 18, "Love your neighbor as yourself."),
('Numbers', 6, 24, "The Lord bless you and keep you."),
('Deuteronomy', 31, 6, "Be strong and courageous. Do not be afraid or terrified."),
('Joshua', 1, 9, "Be strong and courageous. Do not be afraid; do not be discouraged."),
('Judges', 6, 12, "The Lord is with you, mighty warrior."),
('Ruth', 1, 16, "Where you go I will go, and where you stay I will stay."),
('1 Samuel', 16, 7, "Man looks at the outward appearance, but the Lord looks at the heart."),
('2 Samuel', 22, 31, "As for God, his way is perfect."),
('1 Kings', 8, 61, "Let your heart be fully committed to the Lord."),
('2 Kings', 20, 5, "I have heard your prayer and seen your tears; I will heal you."),
('1 Chronicles', 16, 11, "Look to the Lord and his strength; seek his face always."),
('2 Chronicles', 7, 14, "If my people, who are called by my name, will humble themselves and pray."),
('Ezra', 10, 4, "Rise up; this matter is in your hands."),
('Nehemiah', 8, 10, "The joy of the Lord is your strength."),
('Esther', 4, 14, "Perhaps you were born for such a time as this."),
('Job', 19, 25, "I know that my Redeemer lives."),
('Psalms', 46, 1, "God is our refuge and strength, an ever-present help in trouble."),
('Proverbs', 3, 5, "Trust in the Lord with all your heart and lean not on your own understanding."),
('Ecclesiastes', 3, 1, "There is a time for everything, and a season for every activity under the heavens."),
('Song of Solomon', 2, 4, "His banner over me is love."),
('Isaiah', 40, 31, "Those who hope in the Lord will renew their strength."),
('Jeremiah', 29, 11, "For I know the plans I have for you, declares the Lord."),
('Lamentations', 3, 22, "Because of the Lord’s great love we are not consumed."),
('Ezekiel', 36, 26, "I will give you a new heart and put a new spirit in you."),
('Daniel', 6, 22, "My God sent his angel, and he shut the mouths of the lions."),
('Hosea', 6, 6, "I desire mercy, not sacrifice."),
('Joel', 2, 25, "I will repay you for the years the locusts have eaten."),
('Amos', 5, 24, "Let justice roll on like a river, righteousness like a never-failing stream."),
('Obadiah', 1, 15, "The day of the Lord is near for all nations."),
('Jonah', 2, 2, "In my distress I called to the Lord, and he answered me."),
('Micah', 6, 8, "Act justly, love mercy, and walk humbly with your God."),
('Nahum', 1, 7, "The Lord is good, a refuge in times of trouble."),
('Habakkuk', 2, 3, "Though it linger, wait for it; it will certainly come and will not delay."),
('Zephaniah', 3, 17, "The Lord your God is with you, the Mighty Warrior who saves."),
('Haggai', 2, 9, "The glory of this present house will be greater than the former."),
('Zechariah', 4, 6, "Not by might nor by power, but by my Spirit, says the Lord."),
('Malachi', 3, 10, "Test me in this, says the Lord Almighty."),
('Matthew', 11, 28, "Come to me, all you who are weary and burdened, and I will give you rest."),
('Mark', 12, 30, "Love the Lord your God with all your heart."),
('Luke', 6, 31, "Do to others as you would have them do to you."),
('John', 14, 6, "I am the way and the truth and the life."),
('Acts', 1, 8, "You will receive power when the Holy Spirit comes on you."),
('Romans', 8, 28, "In all things God works for the good of those who love him."),
('1 Corinthians', 13, 4, "Love is patient, love is kind."),
('2 Corinthians', 5, 7, "We live by faith, not by sight."),
('Galatians', 5, 22, "The fruit of the Spirit is love, joy, peace, patience, kindness."),
('Ephesians', 2, 8, "For it is by grace you have been saved, through faith."),
('Philippians', 4, 13, "I can do all things through Christ who strengthens me."),
('Colossians', 3, 23, "Whatever you do, work at it with all your heart."),
('1 Thessalonians', 5, 16, "Rejoice always."),
('2 Thessalonians', 3, 3, "The Lord is faithful, and he will strengthen you."),
('1 Timothy', 6, 12, "Fight the good fight of the faith."),
('2 Timothy', 1, 7, "For God has not given us a spirit of fear."),
('Titus', 2, 11, "For the grace of God has appeared that offers salvation to all people."),
('Philemon', 1, 7, "Your love has given me great joy and encouragement."),
('Hebrews', 11, 1, "Faith is confidence in what we hope for."),
('James', 1, 5, "If any of you lacks wisdom, you should ask God."),
('1 Peter', 5, 7, "Cast all your anxiety on him because he cares for you."),
('2 Peter', 3, 9, "The Lord is not slow in keeping his promise."),
('1 John', 4, 19, "We love because he first loved us."),
('2 John', 1, 6, "And this is love: that we walk in obedience to his commands."),
('3 John', 1, 4, "I have no greater joy than to hear that my children are walking in the truth."),
('Jude', 1, 24, "To him who is able to keep you from stumbling."),
('Revelation', 21, 4, "He will wipe every tear from their eyes.");

select * from bible_quotes;


